!!python/object:argparse.Namespace
algo: gcbf+
alpha: 1.0
area_size: 2.0
batch_size: 256
buffer_size: 512
cost_weight: 1.0
debug: false
env: CrazyFlie
eval_epi: 1
eval_interval: 1
gnn_layers: 1
horizon: 32
log_dir: ./logs
loss_action_coef: 3.0e-05
loss_h_dot_coef: 0.01
loss_safe_coef: 1.0
loss_unsafe_coef: 1.0
lr_actor: 1.0e-05
lr_cbf: 0.0001
lr_critic: 0.0001
n_env_test: 32
n_env_train: 16
n_rays: 32
name: null
num_agents: 8
obs: 0
save_interval: 10
seed: 0
steps: 1000
alpha: 1.0
batch_size: 256
eps: 0.02
gnn_layers: 1
horizon: 32
inner_epoch: 8
loss_action_coef: 3.0e-05
loss_h_dot_coef: 0.01
loss_safe_coef: 1.0
loss_unsafe_coef: 1.0
lr_actor: 1.0e-05
lr_cbf: 0.0001
max_grad_norm: 2.0
seed: 0
